### ISSUE TITLE
Unable to create client

### ISSUE THREAD

**Issue by amitpatelx** [BoTreeConsultingTeam/invoiceme#25]
Getting `We're sorry, but something went wrong.` on heroku

**Comment by ParthivPatel-BTC** [comment]
If you face this type of error at "Sign Up" time,  here is the reason and it's solution.

**Reason**: Google was blocking access from unknown location (app in production)
**Solution**: Go to http://www.google.com/accounts/DisplayUnlockCaptcha and click continue (this will grant access for 10 minutes for registering new apps). After this my app in production started sending emails.

**Credentials for gmail test account**:
Email: demo4582@gmail.com
Password: priyam4582


http://stackoverflow.com/questions/18124878/netsmtpauthenticationerror-when-sending-email-from-rails-app-on-staging-envir

**Comment by PragatiDoshi-BTC** [comment]
currently, it is working fine on heroku app.
