### ISSUE TITLE
UI Changes: Sticky Footer

### ISSUE THREAD

**Issue by ParthivPatel-BTC** [BoTreeConsultingTeam/invoiceme#53]
- [ ] Footer should be sticky at the bottom of any page.
- [ ] It should be responsive.

**References** 
http://getbootstrap.com/examples/sticky-footer/
http://getbootstrap.com/2.3.2/examples/sticky-footer-navbar.html
http://stackoverflow.com/questions/17966140/twitter-bootstrap-3-sticky-footer

**Comment by amitpatelx** [comment]
@ParthivPatel-BTC I don't see real use of footer. Please remove it.
