### ISSUE TITLE
Client > New - Keep on getting invalid pincode

### ISSUE THREAD

**Issue by amitpatelx** [BoTreeConsultingTeam/invoiceme#65]
![image](https://cloud.githubusercontent.com/assets/1289894/7835186/6600fd62-0494-11e5-91b6-46c179989eac.png)

I tried with 2 to 8 numeric characters but doesn't work.

Also the error message is not friendly.

**Comment by PragatiDoshi-BTC** [comment]
I have used validates_zipcode gem for validating pincode. Currently it is supporting 159 countries. The codes of the countries and their regex for validations are stored in one lib file in the gem. The link for the codes and regex are shown as below.

https://codeclimate.com/github/dgilperez/validates_zipcode/ValidatesZipcode::CldrRegexpCollection
