### ISSUE TITLE
UI/Functional Issues On Heroku

### ISSUE THREAD

**Issue by ParthivPatel-BTC** [BoTreeConsultingTeam/invoiceme#85]
- [x] https://github.com/BoTreeConsultingTeam/invoiceme/issues/80
- [x] https://github.com/BoTreeConsultingTeam/invoiceme/issues/60
- [x] Clients --> Index
  ![selection_072](https://cloud.githubusercontent.com/assets/5477412/8050809/3105e530-0e91-11e5-939f-6a040a407b76.png)
- [x] Button CSS classes should be same through out application
- [x] As per above screen-shot, listing follow same design pattern for all modules. 
- [x] Error messages should be in proper format in all modules. It is difficult to read the messages. Have a look at following screen-shot.
  ![selection_074](https://cloud.githubusercontent.com/assets/5477412/8050888/5a931246-0e92-11e5-8187-c41b33d9aadf.png)
- [ ] Add `*` for mandatory fields. Have a look at above screen-shot.
- [x] In create/update form, submit button value should be "Save or Update". Change this through out application.
- [x] Users --> New/Edit User form: Textbox margin should be same. Have a look at following screen-shot
  ![selection_075](https://cloud.githubusercontent.com/assets/5477412/8051036/a2d8c4e0-0e94-11e5-90d8-5b88dd53c391.png)
- [x] Apply CSS class on every dropdown through out application.

![selection_077](https://cloud.githubusercontent.com/assets/5477412/8051058/fa5da5b4-0e94-11e5-8e53-5b7eaf6a3328.png)
- [x] Items --> Index page
  ![selection_078](https://cloud.githubusercontent.com/assets/5477412/8051130/3466e134-0e96-11e5-89ec-bbcc496c3fad.png)
  - [x] Remove `Description` column
  - [x] Name column `width: 90%`
  - [x] Action links should be in center and add space between each links.
- [x] Add `disable_with` property on each Submit Buttons through out application.
  http://www.railsonmaui.com/blog/2014/02/23/simple-form-and-disable-processing-by-default/
  http://stackoverflow.com/questions/24549067/how-to-set-html-on-data-disable-with-to-rails-submit-tag
- [x] After sign in --> Change Password
  - [x] Display error messages properly
  - [x] If we enter wrong password as Current password, it should not allow.

![selection_079](https://cloud.githubusercontent.com/assets/5477412/8051455/31b010b0-0e9a-11e5-85b4-29f7c3523d51.png)
- [x] Change as per following screen-shot
  ![selection_081](https://cloud.githubusercontent.com/assets/5477412/8051665/fa65142c-0e9c-11e5-8a44-7bd132ab46c5.png)
-  [x] Tax: New/Edit form - `Parent` part should not display if parent tax not exist.
-  [x] Add `(In %)` just after `Rate` label. See above screen-shot.
-  [x] User Add/Edit Form: Missing validation. Have a look at following screen-shot
  ![selection_083](https://cloud.githubusercontent.com/assets/5477412/8059555/45388f56-0ede-11e5-89b3-d4077e691310.png)

**Comment by PragatiDoshi-BTC** [comment]
Except 80 and 60, this issue will take approximately 1 hr.

**Comment by ParthivPatel-BTC** [comment]
Invoice: New Invoice form
![selection_097](https://cloud.githubusercontent.com/assets/5477412/8124037/36614c50-10f2-11e5-8d9a-9d2b2f44a810.png)
